//! CEG 1.0-RC14 §19.7 conformance vectors — Edge as the SECOND impl reproducing
//! CIRISVerify v5.10.0's authored vectors byte-for-byte. Round-trip green here
//! lifts §19.7 from RC-grade to 1.0.
//!
//! Unlike `conformance_vectors_v19.rs` (where edge AUTHORED the vectors and
//! verify reproduced), §19.7's vectors were authored by CIRISVerify v5.10.0
//! because no edge reference impl predated the §19.7 contract. This file
//! emits edge's locally-generated bytes from the in-tree producer and asserts
//! byte-equality against the committed `conformance_vectors/19_7/*.json`
//! fixtures.

use ciris_edge::holonomic::aggregation::{
    compute_member_commitment, AggregationMetaV1, AGG_META_DOMAIN, AGG_META_VERSION,
};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

const VECTORS_ROOT: &str = "conformance_vectors/19_7";

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(VECTORS_ROOT)
}

fn hex_encode(bytes: &[u8]) -> String {
    use std::fmt::Write;
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        write!(&mut s, "{b:02x}").expect("hex write");
    }
    s
}

fn emit_or_verify<T: Serialize + for<'de> Deserialize<'de> + PartialEq + std::fmt::Debug>(
    relative_path: &str,
    actual: &T,
) {
    let path = vectors_dir().join(relative_path);
    if !path.exists() {
        std::fs::create_dir_all(path.parent().unwrap()).expect("create vector dir");
        let json = serde_json::to_string_pretty(actual).expect("serialize vector");
        std::fs::write(&path, json + "\n").expect("write vector file");
        panic!("vector EMITTED: {relative_path} — commit conformance_vectors/ and re-run");
    }
    let raw = std::fs::read_to_string(&path).expect("read vector file");
    let expected: T = serde_json::from_str(&raw).expect("parse vector file");
    assert_eq!(
        actual, &expected,
        "VECTOR DRIFT at {relative_path} — substrate wire changed without bumping vector"
    );
}

// ──────────────────────────── §19.7.1 AggregationMetaV1 ────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
struct AggregationMetaCanonicalVector {
    vector_id: String,
    description: String,
    domain_separator_hex: String,
    version: u32,
    content_id: String,
    corpus_kind: String,
    tier: u32,
    aggregation_algorithm_id: String,
    source_count: u32,
    source_member_ids: Vec<String>,
    member_commitment_hex: String,
    noise_floor_descriptor: String,
    expected_canonical_bytes_hex: String,
}

#[test]
fn vector_aggregation_meta_canonical_bytes_three_source_pyramid() {
    let source_ids: Vec<String> = ["src-001", "src-002", "src-003"]
        .into_iter()
        .map(String::from)
        .collect();
    let member_commitment = compute_member_commitment(&source_ids);
    let meta = AggregationMetaV1 {
        version: AGG_META_VERSION,
        content_id: "content-root-fixed".to_string(),
        corpus_kind: "trace".to_string(),
        tier: 2,
        aggregation_algorithm_id: "raptorq-pyramid-v1".to_string(),
        source_count: 3,
        member_commitment,
        noise_floor_descriptor: "mean+stddev".to_string(),
    };
    let vector = AggregationMetaCanonicalVector {
        vector_id: "aggregation_meta/canonical_bytes".to_string(),
        description: "AggregationMetaV1 §19.7.1 canonical signing preimage (16-byte AGG-META \
                      domain, u32-lp, big-endian). Matches CIRISVerify v5.10.0's authored \
                      vector byte-for-byte."
            .to_string(),
        domain_separator_hex: hex_encode(AGG_META_DOMAIN),
        version: meta.version,
        content_id: meta.content_id.clone(),
        corpus_kind: meta.corpus_kind.clone(),
        tier: meta.tier,
        aggregation_algorithm_id: meta.aggregation_algorithm_id.clone(),
        source_count: meta.source_count,
        source_member_ids: source_ids,
        member_commitment_hex: hex_encode(&meta.member_commitment),
        noise_floor_descriptor: meta.noise_floor_descriptor.clone(),
        expected_canonical_bytes_hex: hex_encode(&meta.signing_preimage()),
    };
    emit_or_verify("aggregation_meta/canonical_bytes.json", &vector);
}

// ──────────────────────────── §19.7.1.1 member_commitment ────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
struct MemberCommitmentVector {
    vector_id: String,
    description: String,
    source_member_ids: Vec<String>,
    expected_commitment_hex: String,
}

#[test]
fn vector_member_commitment_empty() {
    let root = compute_member_commitment(&[]);
    let vector = MemberCommitmentVector {
        vector_id: "member_commitment/empty".to_string(),
        description: "member_commitment = §19.1 WholenessWitness Merkle over \
                      SHA-256(utf8(member_id)), lexicographic."
            .to_string(),
        source_member_ids: vec![],
        expected_commitment_hex: hex_encode(&root),
    };
    emit_or_verify("member_commitment/empty.json", &vector);
}

#[test]
fn vector_member_commitment_single() {
    let source: Vec<String> = vec!["m1".to_string()];
    let root = compute_member_commitment(&source);
    let vector = MemberCommitmentVector {
        vector_id: "member_commitment/single".to_string(),
        description: "member_commitment = §19.1 WholenessWitness Merkle over \
                      SHA-256(utf8(member_id)), lexicographic."
            .to_string(),
        source_member_ids: source,
        expected_commitment_hex: hex_encode(&root),
    };
    emit_or_verify("member_commitment/single.json", &vector);
}

#[test]
fn vector_member_commitment_three_unsorted() {
    // §19.7.1.1 / §19.1 WW-2: unsorted input MUST produce the same root as
    // sorted input. Verify v5.10.0's vector uses ["m3", "m1", "m2"] and
    // expects 1bfd0a8a... — we MUST reproduce.
    let source: Vec<String> = ["m3", "m1", "m2"].into_iter().map(String::from).collect();
    let root = compute_member_commitment(&source);
    let vector = MemberCommitmentVector {
        vector_id: "member_commitment/three_unsorted".to_string(),
        description: "member_commitment = §19.1 WholenessWitness Merkle over \
                      SHA-256(utf8(member_id)), lexicographic."
            .to_string(),
        source_member_ids: source,
        expected_commitment_hex: hex_encode(&root),
    };
    emit_or_verify("member_commitment/three_unsorted.json", &vector);
}

// ──────────────────────────── §19.7 domain separators ────────────────

#[test]
fn vector_domain_separators() {
    #[allow(clippy::struct_field_names)]
    #[derive(Serialize, Deserialize, Debug, PartialEq, Eq)]
    struct DomainSeparators {
        agg_meta_v1_hex: String,
        agg_meta_v1_len: usize,
    }
    let seps = DomainSeparators {
        agg_meta_v1_hex: hex_encode(AGG_META_DOMAIN),
        agg_meta_v1_len: AGG_META_DOMAIN.len(),
    };
    emit_or_verify("domain_separators.json", &seps);
}
