//! CEG 1.0-RC14 §19.7 conformance vectors — Edge as the SECOND impl reproducing
//! CIRISVerify v5.10.0's authored vectors byte-for-byte. Round-trip green here
//! lifts §19.7 from RC-grade to 1.0.
//!
//! Unlike `conformance_vectors_v19.rs` (where edge AUTHORED the vectors and
//! verify reproduced), §19.7's vectors were authored by CIRISVerify v5.10.0
//! because no edge reference impl predated the §19.7 contract. This file
//! emits edge's locally-generated bytes from the in-tree producer and asserts
//! byte-equality against the committed `conformance_vectors/19_7/*.json`
//! fixtures.

use ciris_edge::holonomic::aggregation::{
    assemble_tier_meta_v2, assemble_tier_meta_v3, compute_member_commitment, mass_commitment,
    mass_to_fixed, AggregationMetaV1, AGG_META_DOMAIN, AGG_META_VERSION, AGG_META_VERSION_V2,
    AGG_META_VERSION_V3, MASS_FIXED_POINT_SCALE,
};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

const VECTORS_ROOT: &str = "conformance_vectors/19_7";

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(VECTORS_ROOT)
}

fn hex_encode(bytes: &[u8]) -> String {
    use std::fmt::Write;
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        write!(&mut s, "{b:02x}").expect("hex write");
    }
    s
}

fn emit_or_verify<T: Serialize + for<'de> Deserialize<'de> + PartialEq + std::fmt::Debug>(
    relative_path: &str,
    actual: &T,
) {
    let path = vectors_dir().join(relative_path);
    if !path.exists() {
        std::fs::create_dir_all(path.parent().unwrap()).expect("create vector dir");
        let json = serde_json::to_string_pretty(actual).expect("serialize vector");
        std::fs::write(&path, json + "\n").expect("write vector file");
        panic!("vector EMITTED: {relative_path} — commit conformance_vectors/ and re-run");
    }
    let raw = std::fs::read_to_string(&path).expect("read vector file");
    let expected: T = serde_json::from_str(&raw).expect("parse vector file");
    assert_eq!(
        actual, &expected,
        "VECTOR DRIFT at {relative_path} — substrate wire changed without bumping vector"
    );
}

// ──────────────────────────── §19.7.1 AggregationMetaV1 ────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
struct AggregationMetaCanonicalVector {
    vector_id: String,
    description: String,
    domain_separator_hex: String,
    version: u32,
    content_id: String,
    corpus_kind: String,
    tier: u32,
    aggregation_algorithm_id: String,
    source_count: u32,
    source_member_ids: Vec<String>,
    member_commitment_hex: String,
    noise_floor_descriptor: String,
    expected_canonical_bytes_hex: String,
}

#[test]
fn vector_aggregation_meta_canonical_bytes_three_source_pyramid() {
    let source_ids: Vec<String> = ["src-001", "src-002", "src-003"]
        .into_iter()
        .map(String::from)
        .collect();
    let member_commitment = compute_member_commitment(&source_ids);
    let meta = AggregationMetaV1 {
        version: AGG_META_VERSION,
        content_id: "content-root-fixed".to_string(),
        corpus_kind: "trace".to_string(),
        tier: 2,
        aggregation_algorithm_id: "raptorq-pyramid-v1".to_string(),
        source_count: 3,
        member_commitment,
        noise_floor_descriptor: "mean+stddev".to_string(),
        // §19.7.1.2 (#167): a v1 tier carries n_eff as a neutral, un-signed
        // placeholder — the v1 preimage below MUST be byte-identical to the
        // pre-#167 layout regardless of this value.
        n_eff: 3,
        // §19.7.1.3 (#191): same discipline — appended to the preimage only iff
        // version >= 3, so the v1 golden vector stays byte-identical.
        max_source_multiplicity: 0,
        mass_commitment: [0u8; 32],
    };
    let vector = AggregationMetaCanonicalVector {
        vector_id: "aggregation_meta/canonical_bytes".to_string(),
        description: "AggregationMetaV1 §19.7.1 canonical signing preimage (16-byte AGG-META \
                      domain, u32-lp, big-endian). Matches CIRISVerify v5.10.0's authored \
                      vector byte-for-byte."
            .to_string(),
        domain_separator_hex: hex_encode(AGG_META_DOMAIN),
        version: meta.version,
        content_id: meta.content_id.clone(),
        corpus_kind: meta.corpus_kind.clone(),
        tier: meta.tier,
        aggregation_algorithm_id: meta.aggregation_algorithm_id.clone(),
        source_count: meta.source_count,
        source_member_ids: source_ids,
        member_commitment_hex: hex_encode(&meta.member_commitment),
        noise_floor_descriptor: meta.noise_floor_descriptor.clone(),
        expected_canonical_bytes_hex: hex_encode(&meta.signing_preimage()),
    };
    emit_or_verify("aggregation_meta/canonical_bytes.json", &vector);
}

// ─────────────────── §19.7.1.2 AggregationMetaV1 v2 (CIRISVerify#167) ──

/// The v2 vector shape — the v1 vector plus the signed effective source
/// count `n_eff` (CIRISEdge#267 / CIRISVerify#167 dominance surface).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
struct AggregationMetaCanonicalVectorV2 {
    vector_id: String,
    description: String,
    domain_separator_hex: String,
    version: u32,
    content_id: String,
    corpus_kind: String,
    tier: u32,
    aggregation_algorithm_id: String,
    source_count: u32,
    source_member_ids: Vec<String>,
    member_commitment_hex: String,
    noise_floor_descriptor: String,
    n_eff: u32,
    expected_canonical_bytes_hex: String,
}

#[test]
fn vector_aggregation_meta_canonical_bytes_v2_three_source_pyramid() {
    // Same fixed three-source pyramid as the v1 vector, assembled through the
    // #267 producer path: version = 2, n_eff computed from balanced per-member
    // masses (inverse-Simpson → n_eff == N == 3), preimage = v1 layout + a
    // trailing u32_be(n_eff).
    let source_ids: Vec<String> = ["src-001", "src-002", "src-003"]
        .into_iter()
        .map(String::from)
        .collect();
    let meta = assemble_tier_meta_v2(
        "content-root-fixed",
        "trace",
        2,
        "raptorq-pyramid-v1",
        &source_ids,
        &[1.0, 1.0, 1.0],
        "mean+stddev",
    );
    assert_eq!(meta.version, AGG_META_VERSION_V2);
    assert_eq!(meta.n_eff, 3, "balanced 3-fold: n_eff == source_count");

    // Cross-impl parity pin: verify v8.7.0's authored golden at
    // src/ciris-verify-core/tests/vectors/holonomic_v19_7/aggregation_meta/canonical_bytes_v2.json.
    // A v2 preimage MUST reproduce it byte-for-byte, independent of the
    // committed edge vector below.
    let verify_authored_hex = "4147472d4d4554412d763100000000000000000200000012636f6e74656e742d726f6f742d66697865640000000574726163650000000200000012726170746f72712d707972616d69642d763100000003a10bc0ec2399f1cd431be79a863385a4b895987dae604aaf2ec3532f3753bd9d0000000b6d65616e2b73746464657600000003";
    let canonical_hex = hex_encode(&meta.signing_preimage());
    assert_eq!(
        canonical_hex, verify_authored_hex,
        "v2 preimage MUST match CIRISVerify v8.7.0's authored vector byte-for-byte"
    );

    let vector = AggregationMetaCanonicalVectorV2 {
        vector_id: "aggregation_meta/canonical_bytes_v2".to_string(),
        description: "AggregationMetaV1 §19.7.1.2 v2 preimage — v1 layout followed by a \
                      trailing big-endian u32(n_eff) (CIRISVerify#167 dominance surface). \
                      Matches CIRISVerify v8.7.0's authored vector byte-for-byte."
            .to_string(),
        domain_separator_hex: hex_encode(AGG_META_DOMAIN),
        version: meta.version,
        content_id: meta.content_id.clone(),
        corpus_kind: meta.corpus_kind.clone(),
        tier: meta.tier,
        aggregation_algorithm_id: meta.aggregation_algorithm_id.clone(),
        source_count: meta.source_count,
        source_member_ids: source_ids,
        member_commitment_hex: hex_encode(&meta.member_commitment),
        noise_floor_descriptor: meta.noise_floor_descriptor.clone(),
        n_eff: meta.n_eff,
        expected_canonical_bytes_hex: canonical_hex,
    };
    emit_or_verify("aggregation_meta/canonical_bytes_v2.json", &vector);
}

// ──────────────────────────── §19.7.1.1 member_commitment ────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
struct MemberCommitmentVector {
    vector_id: String,
    description: String,
    source_member_ids: Vec<String>,
    expected_commitment_hex: String,
}

#[test]
fn vector_member_commitment_empty() {
    let root = compute_member_commitment(&[]);
    let vector = MemberCommitmentVector {
        vector_id: "member_commitment/empty".to_string(),
        description: "member_commitment = §19.1 WholenessWitness Merkle over \
                      SHA-256(utf8(member_id)), lexicographic."
            .to_string(),
        source_member_ids: vec![],
        expected_commitment_hex: hex_encode(&root),
    };
    emit_or_verify("member_commitment/empty.json", &vector);
}

#[test]
fn vector_member_commitment_single() {
    let source: Vec<String> = vec!["m1".to_string()];
    let root = compute_member_commitment(&source);
    let vector = MemberCommitmentVector {
        vector_id: "member_commitment/single".to_string(),
        description: "member_commitment = §19.1 WholenessWitness Merkle over \
                      SHA-256(utf8(member_id)), lexicographic."
            .to_string(),
        source_member_ids: source,
        expected_commitment_hex: hex_encode(&root),
    };
    emit_or_verify("member_commitment/single.json", &vector);
}

#[test]
fn vector_member_commitment_three_unsorted() {
    // §19.7.1.1 / §19.1 WW-2: unsorted input MUST produce the same root as
    // sorted input. Verify v5.10.0's vector uses ["m3", "m1", "m2"] and
    // expects 1bfd0a8a... — we MUST reproduce.
    let source: Vec<String> = ["m3", "m1", "m2"].into_iter().map(String::from).collect();
    let root = compute_member_commitment(&source);
    let vector = MemberCommitmentVector {
        vector_id: "member_commitment/three_unsorted".to_string(),
        description: "member_commitment = §19.1 WholenessWitness Merkle over \
                      SHA-256(utf8(member_id)), lexicographic."
            .to_string(),
        source_member_ids: source,
        expected_commitment_hex: hex_encode(&root),
    };
    emit_or_verify("member_commitment/three_unsorted.json", &vector);
}

// ──────────────────────────── §19.7 domain separators ────────────────

#[test]
fn vector_domain_separators() {
    #[allow(clippy::struct_field_names)]
    #[derive(Serialize, Deserialize, Debug, PartialEq, Eq)]
    struct DomainSeparators {
        agg_meta_v1_hex: String,
        agg_meta_v1_len: usize,
    }
    let seps = DomainSeparators {
        agg_meta_v1_hex: hex_encode(AGG_META_DOMAIN),
        agg_meta_v1_len: AGG_META_DOMAIN.len(),
    };
    emit_or_verify("domain_separators.json", &seps);
}

// ─── §19.7.1.3 v3 — the R9 cross-impl pin (CIRISConformance#74) ──────────
//
// CIRISVerify AUTHORED `tests/vectors/holonomic_v19_7/aggregation_meta/
// canonical_bytes_v3.json`. Edge is the SECOND impl and must reproduce it
// byte-for-byte. The expected bytes are hard-pinned HERE (not read from a
// shared file) so the two impls are genuinely cross-checked — a shared fixture
// that both sides regenerate would drift silently, and this preimage backs a
// SIGNED field (`max_source_multiplicity` + `mass_commitment`). A fork here is
// a fork in admissibility: one impl admits a fold the other rejects.

/// CIRISVerify's authored v3 vector (`aggregation_meta/canonical_bytes_v3`).
const V3_EXPECTED_CANONICAL_BYTES_HEX: &str = "4147472d4d4554412d763100000000000000000300000012636f6e74656e742d726f6f742d66697865640000000574726163650000000200000012726170746f72712d707972616d69642d763100000003a10bc0ec2399f1cd431be79a863385a4b895987dae604aaf2ec3532f3753bd9d0000000b6d65616e2b7374646465760000000300000001a00af73b1e112530ceb7c5af8f806b45af264978e448b3810cefb3f9f79cd3c5";
const V3_MEMBER_COMMITMENT_HEX: &str =
    "a10bc0ec2399f1cd431be79a863385a4b895987dae604aaf2ec3532f3753bd9d";
const V3_MASS_COMMITMENT_HEX: &str =
    "a00af73b1e112530ceb7c5af8f806b45af264978e448b3810cefb3f9f79cd3c5";
/// The vector's per-member masses. NOTE they do not sum to 1 — the vector pins
/// the ENCODING, not a fold's normalization; `mass_to_fixed` is what the
/// commitment binds.
const V3_MASSES: [f64; 3] = [1.0, 0.5, 0.25];
const V3_MASSES_FIXED: [u64; 3] = [1_000_000, 500_000, 250_000];

fn v3_source_ids() -> Vec<String> {
    ["src-001", "src-002", "src-003"]
        .into_iter()
        .map(String::from)
        .collect()
}

/// The §19.7.1.3 v3 preimage reproduces CIRISVerify's authored vector
/// byte-for-byte: v2 layout + `u32_be(max_source_multiplicity)` +
/// `mass_commitment[32]`.
#[test]
fn vector_aggregation_meta_v3_canonical_bytes_matches_verify() {
    let ids = v3_source_ids();
    let meta = AggregationMetaV1 {
        version: AGG_META_VERSION_V3,
        content_id: "content-root-fixed".to_string(),
        corpus_kind: "trace".to_string(),
        tier: 2,
        aggregation_algorithm_id: "raptorq-pyramid-v1".to_string(),
        source_count: 3,
        member_commitment: compute_member_commitment(&ids),
        noise_floor_descriptor: "mean+stddev".to_string(),
        n_eff: 3,
        max_source_multiplicity: 1,
        mass_commitment: mass_commitment(
            &ids.iter().cloned().zip(V3_MASSES_FIXED).collect::<Vec<_>>(),
        ),
    };
    assert_eq!(
        hex_encode(&meta.signing_preimage()),
        V3_EXPECTED_CANONICAL_BYTES_HEX,
        "edge's v3 preimage MUST reproduce CIRISVerify's authored vector byte-for-byte \
         — a fork here forks admissibility (CIRISConformance#74)"
    );
}

/// The two v3 commitments edge computes match verify's authored roots, and the
/// fixed-point mass scale is the pinned 1e6.
#[test]
fn vector_aggregation_meta_v3_commitments_match_verify() {
    let ids = v3_source_ids();
    assert_eq!(
        hex_encode(&compute_member_commitment(&ids)),
        V3_MEMBER_COMMITMENT_HEX,
        "member_commitment (Merkle over ids) must match verify"
    );
    // mass_to_fixed is the pinned 1e6 scale — the commitment binds these.
    let fixed: Vec<u64> = V3_MASSES.iter().map(|m| mass_to_fixed(*m)).collect();
    assert_eq!(
        fixed,
        V3_MASSES_FIXED.to_vec(),
        "mass_to_fixed must use the pinned MASS_FIXED_POINT_SCALE ({MASS_FIXED_POINT_SCALE})"
    );
    let leaves: Vec<(String, u64)> = ids.iter().cloned().zip(fixed).collect();
    assert_eq!(
        hex_encode(&mass_commitment(&leaves)),
        V3_MASS_COMMITMENT_HEX,
        "mass_commitment (Merkle over (member_id, mass_fixed)) must match verify"
    );
}

/// The PRODUCER path: `assemble_tier_meta_v3` wires the measured surface into
/// the exact slots verify's vector pins — same commitments, version 3, and the
/// multiplicity carried through. (n_eff is derived from the masses by the
/// producer, so it is asserted against the producer's own inverse-Simpson, not
/// the vector's independently-authored field.)
#[test]
fn v3_producer_reproduces_the_vector_commitments() {
    let ids = v3_source_ids();
    let meta = assemble_tier_meta_v3(
        "content-root-fixed",
        "trace",
        2,
        "raptorq-pyramid-v1",
        &ids,
        &V3_MASSES,
        1,
        "mean+stddev",
    );
    assert_eq!(meta.version, AGG_META_VERSION_V3);
    assert_eq!(meta.max_source_multiplicity, 1);
    assert_eq!(
        hex_encode(&meta.member_commitment),
        V3_MEMBER_COMMITMENT_HEX
    );
    assert_eq!(hex_encode(&meta.mass_commitment), V3_MASS_COMMITMENT_HEX);
}
