// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_CRATE_VERSION
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_CRATE_VERSION
RustBuffer uniffi_ciris_edge_fn_func_crate_version(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_CURRENT_RATCHET_ID
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_CURRENT_RATCHET_ID
RustBuffer uniffi_ciris_edge_fn_func_current_ratchet_id(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_IDENTITY_HASH
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_IDENTITY_HASH
RustBuffer uniffi_ciris_edge_fn_func_identity_hash(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_IDENTITY_PUBKEYS
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_IDENTITY_PUBKEYS
RustBuffer uniffi_ciris_edge_fn_func_identity_pubkeys(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_LAST_ROTATION_AT
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_LAST_ROTATION_AT
RustBuffer uniffi_ciris_edge_fn_func_last_rotation_at(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_METRICS_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_METRICS_SNAPSHOT
RustBuffer uniffi_ciris_edge_fn_func_metrics_snapshot(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PATH_TABLE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PATH_TABLE
RustBuffer uniffi_ciris_edge_fn_func_path_table(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_ADD
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_ADD
RustBuffer uniffi_ciris_edge_fn_func_peer_add(RustBuffer key_id, RustBuffer pubkey_ed25519_base64, RustBuffer transport_identity, RustBuffer policy, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_GET
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_GET
RustBuffer uniffi_ciris_edge_fn_func_peer_get(RustBuffer key_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_HEALTH_SUMMARY
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_HEALTH_SUMMARY
RustBuffer uniffi_ciris_edge_fn_func_peer_health_summary(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_LIST
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_LIST
RustBuffer uniffi_ciris_edge_fn_func_peer_list(RustBuffer filter, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_PROBE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_PROBE
RustBuffer uniffi_ciris_edge_fn_func_peer_probe(RustBuffer key_id, uint64_t timeout_ms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_REMOVE
void uniffi_ciris_edge_fn_func_peer_remove(RustBuffer handle, int8_t hard, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_SET_ALIAS
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_SET_ALIAS
void uniffi_ciris_edge_fn_func_peer_set_alias(RustBuffer key_id, RustBuffer alias, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_SET_NOTES
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_SET_NOTES
void uniffi_ciris_edge_fn_func_peer_set_notes(RustBuffer key_id, RustBuffer notes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_SET_POLICY
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_SET_POLICY
void uniffi_ciris_edge_fn_func_peer_set_policy(RustBuffer handle, RustBuffer policy, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_SET_TRUST
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_PEER_SET_TRUST
void uniffi_ciris_edge_fn_func_peer_set_trust(RustBuffer key_id, RustBuffer trust, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_QUEUE_DEPTH
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_QUEUE_DEPTH
RustBuffer uniffi_ciris_edge_fn_func_queue_depth(RustBuffer delivery_class, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_RECENT_ERRORS
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_RECENT_ERRORS
RustBuffer uniffi_ciris_edge_fn_func_recent_errors(uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_RECENT_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_RECENT_EVENTS
RustBuffer uniffi_ciris_edge_fn_func_recent_events(uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_ADD
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_ADD
RustBuffer uniffi_ciris_edge_fn_func_transport_add(RustBuffer spec, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_CONFIG_BLOB
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_CONFIG_BLOB
RustBuffer uniffi_ciris_edge_fn_func_transport_config_blob(RustBuffer handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_DISABLE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_DISABLE
void uniffi_ciris_edge_fn_func_transport_disable(RustBuffer handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_ENABLE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_ENABLE
void uniffi_ciris_edge_fn_func_transport_enable(RustBuffer handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_HEALTH
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_HEALTH
RustBuffer uniffi_ciris_edge_fn_func_transport_health(RustBuffer handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_LIST
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_LIST
RustBuffer uniffi_ciris_edge_fn_func_transport_list(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_REMOVE
void uniffi_ciris_edge_fn_func_transport_remove(RustBuffer handle, int8_t drain, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_SET_MODE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_SET_MODE
void uniffi_ciris_edge_fn_func_transport_set_mode(RustBuffer handle, RustBuffer mode, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_STATS
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_FN_FUNC_TRANSPORT_STATS
RustBuffer uniffi_ciris_edge_fn_func_transport_stats(RustBuffer handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUSTBUFFER_ALLOC
RustBuffer ffi_ciris_edge_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_ciris_edge_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUSTBUFFER_FREE
void ffi_ciris_edge_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUSTBUFFER_RESERVE
RustBuffer ffi_ciris_edge_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_U8
void ffi_ciris_edge_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_U8
void ffi_ciris_edge_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_U8
void ffi_ciris_edge_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_ciris_edge_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_I8
void ffi_ciris_edge_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_I8
void ffi_ciris_edge_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_I8
void ffi_ciris_edge_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_ciris_edge_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_U16
void ffi_ciris_edge_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_U16
void ffi_ciris_edge_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_U16
void ffi_ciris_edge_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_ciris_edge_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_I16
void ffi_ciris_edge_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_I16
void ffi_ciris_edge_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_I16
void ffi_ciris_edge_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_ciris_edge_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_U32
void ffi_ciris_edge_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_U32
void ffi_ciris_edge_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_U32
void ffi_ciris_edge_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_ciris_edge_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_I32
void ffi_ciris_edge_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_I32
void ffi_ciris_edge_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_I32
void ffi_ciris_edge_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_ciris_edge_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_U64
void ffi_ciris_edge_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_U64
void ffi_ciris_edge_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_U64
void ffi_ciris_edge_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_ciris_edge_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_I64
void ffi_ciris_edge_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_I64
void ffi_ciris_edge_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_I64
void ffi_ciris_edge_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_ciris_edge_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_F32
void ffi_ciris_edge_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_F32
void ffi_ciris_edge_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_F32
void ffi_ciris_edge_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_F32
float ffi_ciris_edge_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_F64
void ffi_ciris_edge_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_F64
void ffi_ciris_edge_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_F64
void ffi_ciris_edge_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_F64
double ffi_ciris_edge_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_ciris_edge_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_ciris_edge_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_ciris_edge_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_ciris_edge_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_POLL_VOID
void ffi_ciris_edge_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_CANCEL_VOID
void ffi_ciris_edge_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_FREE_VOID
void ffi_ciris_edge_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_RUST_FUTURE_COMPLETE_VOID
void ffi_ciris_edge_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_CRATE_VERSION
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_CRATE_VERSION
uint16_t uniffi_ciris_edge_checksum_func_crate_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_CURRENT_RATCHET_ID
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_CURRENT_RATCHET_ID
uint16_t uniffi_ciris_edge_checksum_func_current_ratchet_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_IDENTITY_HASH
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_IDENTITY_HASH
uint16_t uniffi_ciris_edge_checksum_func_identity_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_IDENTITY_PUBKEYS
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_IDENTITY_PUBKEYS
uint16_t uniffi_ciris_edge_checksum_func_identity_pubkeys(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_LAST_ROTATION_AT
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_LAST_ROTATION_AT
uint16_t uniffi_ciris_edge_checksum_func_last_rotation_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_METRICS_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_METRICS_SNAPSHOT
uint16_t uniffi_ciris_edge_checksum_func_metrics_snapshot(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PATH_TABLE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PATH_TABLE
uint16_t uniffi_ciris_edge_checksum_func_path_table(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_ADD
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_ADD
uint16_t uniffi_ciris_edge_checksum_func_peer_add(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_GET
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_GET
uint16_t uniffi_ciris_edge_checksum_func_peer_get(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_HEALTH_SUMMARY
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_HEALTH_SUMMARY
uint16_t uniffi_ciris_edge_checksum_func_peer_health_summary(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_LIST
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_LIST
uint16_t uniffi_ciris_edge_checksum_func_peer_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_PROBE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_PROBE
uint16_t uniffi_ciris_edge_checksum_func_peer_probe(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_REMOVE
uint16_t uniffi_ciris_edge_checksum_func_peer_remove(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_SET_ALIAS
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_SET_ALIAS
uint16_t uniffi_ciris_edge_checksum_func_peer_set_alias(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_SET_NOTES
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_SET_NOTES
uint16_t uniffi_ciris_edge_checksum_func_peer_set_notes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_SET_POLICY
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_SET_POLICY
uint16_t uniffi_ciris_edge_checksum_func_peer_set_policy(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_SET_TRUST
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_PEER_SET_TRUST
uint16_t uniffi_ciris_edge_checksum_func_peer_set_trust(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_QUEUE_DEPTH
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_QUEUE_DEPTH
uint16_t uniffi_ciris_edge_checksum_func_queue_depth(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_RECENT_ERRORS
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_RECENT_ERRORS
uint16_t uniffi_ciris_edge_checksum_func_recent_errors(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_RECENT_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_RECENT_EVENTS
uint16_t uniffi_ciris_edge_checksum_func_recent_events(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_ADD
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_ADD
uint16_t uniffi_ciris_edge_checksum_func_transport_add(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_CONFIG_BLOB
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_CONFIG_BLOB
uint16_t uniffi_ciris_edge_checksum_func_transport_config_blob(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_DISABLE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_DISABLE
uint16_t uniffi_ciris_edge_checksum_func_transport_disable(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_ENABLE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_ENABLE
uint16_t uniffi_ciris_edge_checksum_func_transport_enable(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_HEALTH
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_HEALTH
uint16_t uniffi_ciris_edge_checksum_func_transport_health(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_LIST
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_LIST
uint16_t uniffi_ciris_edge_checksum_func_transport_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_REMOVE
uint16_t uniffi_ciris_edge_checksum_func_transport_remove(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_SET_MODE
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_SET_MODE
uint16_t uniffi_ciris_edge_checksum_func_transport_set_mode(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_STATS
#define UNIFFI_FFIDEF_UNIFFI_CIRIS_EDGE_CHECKSUM_FUNC_TRANSPORT_STATS
uint16_t uniffi_ciris_edge_checksum_func_transport_stats(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIRIS_EDGE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_CIRIS_EDGE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_ciris_edge_uniffi_contract_version(void
    
);
#endif

